--- #YAML:1.0
name:               Path-Extended
version:            0.01
abstract:           yet another Path class
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Data::Dump:           0
    Encode:               0
    Exporter::Lite:       0
    Fcntl:                0
    File::Basename:       0
    File::Copy::Recursive:  0
    File::Find::Rule:     0
    File::Path:           0
    File::Spec:           0
    File::stat:           0
    IO::Handle:           0
    Scalar::Util:         0
    Test::Classy:         0.04
    Test::More:           0.47
    Test::UseAllModules:  0.09
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
